{{- if not .Values.digitalocean.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digitalocean-exporter.fullname" . }}
  labels:
    {{- include "digitalocean-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.digitalocean.existingSecretKey }}: {{ required "digitalocean.token or digitalocean.existingSecret is required" .Values.digitalocean.token | quote }}
{{- end }}
