apiVersion: v1
kind: Service
metadata:
  name: {{ include "digitalocean-exporter.fullname" . }}
  labels:
    {{- include "digitalocean-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "digitalocean-exporter.selectorLabels" . | nindent 4 }}
