apiVersion: v2
name: digitalocean-exporter
description: Prometheus exporter for DigitalOcean
type: application
version: 0.3.0
appVersion: "0.3.0"
home: https://github.com/kozaktomas/digitalocean_exporter
sources:
  - https://github.com/kozaktomas/digitalocean_exporter
maintainers:
  - name: Tomas Kozak
    email: kozak@talko.cz
